version: "3.4"
services:
  web:
    image: ${DOCKER_REGISTRY}/www.${PRIMARY_DOMAIN}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.www-http.rule=Host(`www.${PRIMARY_DOMAIN}`) || Host(`${PRIMARY_DOMAIN}`)
        - traefik.http.routers.www-http.entrypoints=http
        - traefik.http.routers.www-http.middlewares=https-redirect
        - traefik.http.routers.www-https.rule=Host(`www.${PRIMARY_DOMAIN}`) || Host(`${PRIMARY_DOMAIN}`)
        - traefik.http.routers.www-https.entrypoints=https
        - traefik.http.routers.www-https.tls=true
        - traefik.http.routers.www-https.tls.certresolver=le
        - traefik.http.services.www.loadbalancer.server.port=8080
        - traefik.http.routers.www-https.middlewares=security-headers
        #- traefik.http.middlewares.www-csp.headers.contentsecuritypolicy=default-src 'none'; img-src 'self' https://i.postimg.cc; script-src 'self'; style-src 'self'
    restart: unless-stopped
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
